version: "3.8"

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n_local
    restart: unless-stopped
    ports:
      - "5678:5678"   # déjalo así por ahora, ayuda para pruebas
    environment:
      - TZ=America/Monterrey
      - GENERIC_TIMEZONE=America/Monterrey
      - N8N_HOST=n8n.agsoftweb.com.mx
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://n8n.agsoftweb.com.mx/
      - N8N_EDITOR_BASE_URL=https://n8n.agsoftweb.com.mx/
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
    user: "1000:1000"
    volumes:
      - ./n8n_data:/home/node/.n8n
      - ./files:/files
    networks:
      - appnetwork

networks:
  appnetwork:
    external: true
